version: '3'
services:
  db:
    image: mysql:5.7.28
    environment: 
      MYSQL_DATABASE: tweets
      MYSQL_ROOT_PASSWORD: secret
    volumes: 
      - ./fixture.sql:/docker-entrypoint-initdb.d/fixture.sql
    ports: 
      - "2000:3306"
  
  database_cache:
    image: redis:5.0.7
    ports:
      - "6000:6379"
    command: 'redis-server --maxmemory 1mb --maxmemory-policy allkeys-lru'
      
  index_server:
    image: redis:5.0.7
    ports:
      - "4000:6379"
      
  index_builder:
    image: redis:5.0.7
    ports:
      - "5000:6379"

  application:
    build: .
    restart: always
    command: 'npm run start:dev'
    environment: 
      PORT: 3000
      MYSQL_HOST_SHARD_1: db
      MYSQL_HOST_SHARD_2: db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: tweets
      MYSQL_CONNECTION_LIMIT: 10
      MYSQL_DEBUG: null
      INDEX_SERVER_SHARD_1: 'redis://index_server:6379/0'
      INDEX_SERVER_SHARD_2: 'redis://index_server:6379/0'
      INDEX_SERVER_SHARD_3: 'redis://index_server:6379/0'
      INDEX_SERVER_SHARD_4: 'redis://index_server:6379/0'
      DATABASE_CACHE: 'redis://database_cache:6379/0'
      INDEX_BUILDER: 'redis://index_builder:6379/0'
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on: 
      - db
      - database_cache
      - index_server
      - index_builder