version: '3'
services:
  db:
    image: mysql:8.0.18
    environment: 
      MYSQL_DATABASE: tweets
      MYSQL_ROOT_PASSWORD: secret
    ports: 
      - "2000:3306"
      
  application:
    build: .
    environment: 
      PORT: 3000
      MYSQL_DATABASE: tweets
      MYSQL_ROOT_PASSWORD: secret
    ports:
    - "3000:3000"
    volumes:
    - .:/code
    depends_on: 
      - db
      - index_server
      - index_builder
  index_server:
    image: redis
    environment: 
      PORT: 4000
    ports:
    - "4000:4000"
    volumes:
    - .:/code
  index_builder:
    image: redis
    environment: 
      PORT: 5000
    ports:
    - "5000:5000"
    volumes:
    - .:/code