version: '3'
services:
  db:
    image: mysql:8.0.18
    environment: 
      MYSQL_DATABASE: tweets
      MYSQL_ROOT_PASSWORD: secret
    ports: 
      - "2000:3306"
  
  database_cache:
    image: redis
    ports:
      - "6000:6379"
      
  index_server:
    image: redis
    ports:
      - "4000:6379"
      
  index_builder:
    image: redis
    ports:
      - "5000:6379"

  application:
    build: .
    restart: always
    environment: 
      PORT: 3000
      MYSQL_HOST: host,
      MYSQL_ROOT_PASSWORD: secret,
      MYSQL_DATABASE: tweets,
      MYSQL_CONNECTION_LIMIT: 10
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on: 
      - db
      - index_server
      - index_builder